name: rlcar
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pip:
      - tensorflow==1.15.0
      - keras==2.2.4
      - numpy==1.16.4
      - scipy==1.2.1
      - matplotlib==3.0.3
      - opencv-python==4.1.0.25
      - pygame==1.9.6
      - h5py==2.10.0
      - pillow==6.0.0
